### ISSUE TITLE
Set light vs dark as two themes

### ISSUE THREAD

**Issue by JoseConseco** [Mofiqul/adwaita.nvim#7]
Hi, I wish I could switch from adwaita-light to adwaita-dark using : 
`:colorscheme adwaita-light   (or adwaita-dark) 
Imo its more user friendly to change theme this way, rather than use config option and restart nivm (unless I'm missing something).

**Comment by Mofiqul** [comment]
Now you can use `:set background=light` or `:set background=dark` to change the theme. Please see https://github.com/Mofiqul/adwaita.nvim/pull/6

**Comment by JoseConseco** [comment]
ok, thx. Still I think having two themes to choose form would be cool - eg. when using telescope - themes picker. Vs. now having to seth background. Maybe in future ; )

**Comment by Mofiqul** [comment]
Telescope idea I like it. We can discuss. I dont want to bother everyone by changing api

**Comment by JoseConseco** [comment]
Well, there is  command in [telescope](https://github.com/nvim-telescope/telescope.nvim#vim-pickers)
`:Telescope colorscheme<CR>`
It will show you list of all available themes. Themes I get usually have 2 (or more) variants eg:  dayfox, nightfox,  or github-light,  github-dark.
For backward compatibility,  maybe you could leave adwaita theme as it is (with background setting defining light vs dark) and you could add : adwaita-light, adwaita-dark.  Its not optimal since we would get 3 themes,  but its backward compatible.

**Comment by Slotos** [comment]
Having colorscheme set background is rarely warranted.

I use `:Telescope colorscheme` myself, and with [vim-unimpaired](https://github.com/tpope/vim-unimpaired), a quick `yob` toggles the background.
Moreover, respecting background setting allows for an easy "integration" for a lack of better word with plugins like [auto-dark-mode](https://github.com/f-person/auto-dark-mode.nvim). Drop in a new theme and it will simply work.

As an extra feature, if background is not set in the config, vim determines whether to initialize dark or light from terminal settings. Meaning, if you use colorschemes that implement both light and dark variants, you will never get blasted with full lumens of your screen in the middle of a midnight editing session, even if you change the colors.

Nightfox and github are cases of themes working around perfectly sane defaults, likely because colorscheme reloading  behaviour of the background option is a single sentence in sea of vim documentation.

-------

That aside, you can create a new `colors/adwaita-dark.lua` file in your config:
```lua
local adwaita_dark = require'adwaita.dark'

vim.cmd("hi clear")

if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "adwaita-dark"

adwaita_dark.set()
```

Lualine will need a similar file, but then you're set.
